spring:
  servlet:
    multipart:
      enabled: true             # MultipartFile 업로드 가능
      file-size-threshold: 2KB  # 파일이 메모리에 기록되는 임계값
      max-file-size: 500MB      # 파일의 최대 사이즈
      max-request-size: 515MB   # 요청의 최대 사이즈

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:s3-test;MODE=MYSQL;
    username: sa
    password:

# logging.level.org.apache.coyote.http11: debug

file:
  upload-dir: src/main/resources/images